language: cpp
dist: xenial
compiler: gcc

install: 
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default

services:
 - xvfb

script: 
  # Build test
  - qmake -qt=qt5 travis_qmake_gcc_cpp14_qt5_qtest_test.pro
  - make --silent
  # Build normal
  - qmake -qt=qt5 travis_qmake_gcc_cpp14_qt5_qtest.pro
  - make --silent
  # Run test
  - ./travis_qmake_gcc_cpp14_qt5_qtest_test
